//package com.arcsoft.arcfacedemo.db;
//
//import java.util.Map;
//
//import org.greenrobot.greendao.AbstractDao;
//import org.greenrobot.greendao.AbstractDaoSession;
//import org.greenrobot.greendao.database.Database;
//import org.greenrobot.greendao.identityscope.IdentityScopeType;
//import org.greenrobot.greendao.internal.DaoConfig;
//
//import com.arcsoft.arcfacedemo.db.model.FaceEntity;
//import com.arcsoft.arcfacedemo.db.model.LongTermPass;
//import com.arcsoft.arcfacedemo.db.model.LongTermRecords;
//import com.arcsoft.arcfacedemo.db.model.TemporaryCardRecords;
//
//import com.arcsoft.arcfacedemo.db.FaceEntityDao;
//import com.arcsoft.arcfacedemo.db.LongTermPassDao;
//import com.arcsoft.arcfacedemo.db.LongTermRecordsDao;
//import com.arcsoft.arcfacedemo.db.TemporaryCardRecordsDao;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
//
///**
// * {@inheritDoc}
// *
// * @see org.greenrobot.greendao.AbstractDaoSession
// */
//public class DaoSession extends AbstractDaoSession {
//
//    private final DaoConfig faceEntityDaoConfig;
//    private final DaoConfig longTermPassDaoConfig;
//    private final DaoConfig longTermRecordsDaoConfig;
//    private final DaoConfig temporaryCardRecordsDaoConfig;
//
//    private final FaceEntityDao faceEntityDao;
//    private final LongTermPassDao longTermPassDao;
//    private final LongTermRecordsDao longTermRecordsDao;
//    private final TemporaryCardRecordsDao temporaryCardRecordsDao;
//
//    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
//            daoConfigMap) {
//        super(db);
//
//        faceEntityDaoConfig = daoConfigMap.get(FaceEntityDao.class).clone();
//        faceEntityDaoConfig.initIdentityScope(type);
//
//        longTermPassDaoConfig = daoConfigMap.get(LongTermPassDao.class).clone();
//        longTermPassDaoConfig.initIdentityScope(type);
//
//        longTermRecordsDaoConfig = daoConfigMap.get(LongTermRecordsDao.class).clone();
//        longTermRecordsDaoConfig.initIdentityScope(type);
//
//        temporaryCardRecordsDaoConfig = daoConfigMap.get(TemporaryCardRecordsDao.class).clone();
//        temporaryCardRecordsDaoConfig.initIdentityScope(type);
//
//        faceEntityDao = new FaceEntityDao(faceEntityDaoConfig, this);
//        longTermPassDao = new LongTermPassDao(longTermPassDaoConfig, this);
//        longTermRecordsDao = new LongTermRecordsDao(longTermRecordsDaoConfig, this);
//        temporaryCardRecordsDao = new TemporaryCardRecordsDao(temporaryCardRecordsDaoConfig, this);
//
//        registerDao(FaceEntity.class, faceEntityDao);
//        registerDao(LongTermPass.class, longTermPassDao);
//        registerDao(LongTermRecords.class, longTermRecordsDao);
//        registerDao(TemporaryCardRecords.class, temporaryCardRecordsDao);
//    }
//
//    public void clear() {
//        faceEntityDaoConfig.clearIdentityScope();
//        longTermPassDaoConfig.clearIdentityScope();
//        longTermRecordsDaoConfig.clearIdentityScope();
//        temporaryCardRecordsDaoConfig.clearIdentityScope();
//    }
//
//    public FaceEntityDao getFaceEntityDao() {
//        return faceEntityDao;
//    }
//
//    public LongTermPassDao getLongTermPassDao() {
//        return longTermPassDao;
//    }
//
//    public LongTermRecordsDao getLongTermRecordsDao() {
//        return longTermRecordsDao;
//    }
//
//    public TemporaryCardRecordsDao getTemporaryCardRecordsDao() {
//        return temporaryCardRecordsDao;
//    }
//
//}
