package com.arcsoft.arcfacedemo.entity;

public class LongPassCard {
    public String id;
    public String applyId;
    public String idCode;
    public String cardId;
    public int score;
    public int status;
    public int type;
    public String userId;
    public String companyId;
    public String orgId;
    public String nickname;
    public String companyName;
    public String orgName;
    public String expiryDate;
    public String[] areaRootIds;
    public String[] areaRootCodes;
    public String[] areaIds;
    public String[] areaCodes;
    public String startDate;
    public LeadingPeople[] leadingPeople;
    public String photo;
    public byte[] photoBytes;
    public String[] leadingPeopleId;
    public String idNo;
    public String checkPhoto;
    public byte[] checkPhotoBytes;
    public String unitName;
    public int templateType;
    public boolean isBlacklist;
    public boolean isWithhold;
    public boolean isWithdraw;
    public String withholdStartDate;
    public String withholdEndDate;
    public String cardIdLong;
    public String[] areaDisplayCode;
    public String businessScope;
    public int sex;
    public String updateTime;
}
